# Welcome to Jekyll!
#

# Site settings
title: UC Jazz

description: |
  UC Jazz Ensembles is dedicated to the  
  performance, study, and promotion of  
  jazz at UC Berkeley.

owner: UC Jazz # or company name
#first_published: 2016 # if migrating another site, the year of your first publish
email: ucjazzensembles@gmail.com
baseurl: "/ucjazz_site" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
social:
  # twitter: https://twitter.com/<username>
  # github: https://github.com/<username>
  # linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/ucjazz/
  # google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
